### ISSUE TITLE
is possible to implement :parent ?

### ISSUE THREAD

**Issue by scorninpc** [voku/simple_html_dom#100]
#### What is this feature about (expected vs actual behaviour)?
I know thats exists `parent()` method, but its possible to implement that on selector, like this https://api.jquery.com/parent-selector/ ?

#### How can I reproduce it?
when use `$dom->findOne('.details > div:nth-child(4) > div b:contains("Local"):parent');` throw exception: `Pseudo-class "parent" not supported.`

**Comment by scorninpc** [comment]
I dont know if this is the best solution, but it's a ideia, as the pseudo selector doesn't work

```php
$find = new \voku\helper\HtmlDomParser($html);

// explode the :parent
$parents = explode(":parent", $selector);

// loop between parts
foreach($parents as $index => $sel) {
  $find = $find->findOne($sel);
  $find = $find->parent();
}
$result = $find->text;
```

what do you guys think?

**Comment by voku** [comment]
Mostly we depend on CssSelector (a Symfony Component that Converts CSS selectors to XPath expressions) here. And pseudo selectors are only partly supported. Maybe we could Hck something with the parent method (did it work for you)? But in most cases I would try to avoid this special selectors, if possible.
