### ISSUE TITLE
Instruction on how to use simple_html_dom without Composer

### ISSUE THREAD

**Issue by stgoos** [voku/simple_html_dom#22]
@voku, I just stumbled upon your version of simple_html_dom and I love the fact that it based on PHP 7.

Perhaps it's good to include a little bit of information for those who are not familiar with Composer and/or those who don't have Composer available on their webhost.

I'm one who lands in both categories BUT I found php-download.com after an altered search request in Google. It basically allows one to download the package with everything that Composer would do.

The direct link to your project is:
https://php-download.com/package/voku/simple_html_dom

And in case one would quickly download the latest dev version for usage in their own project then this is the link:

https://php-download.com/downloads/download?vendor=voku&package=simple_html_dom&version=9999999-dev&downloadType=REQUIRE

Cheers!

**Comment by voku** [comment]
It dosn't matter if you ssh access or not, because you can (maybe should for products, not for libaries) install the composer packages locally and push your code + the vendor code together.

**Comment by GeekVisit** [comment]
Sorry, I don't understand the answer ? What does "push your code + the vendor code" together mean ?

**Comment by voku** [comment]
> Sorry, I don't understand the answer ? What does "push your code + the vendor code" together mean ?

You can install your dependencies (vendor code) locally with your computer and then you add / push them into your VCS (version control system e.g. git).
