### ISSUE TITLE
script truncates "\r" from "\r\n" in $_POST variables

### ISSUE THREAD

**Issue by zomar76** [voku/simple_html_dom#28]
just after
require_once __DIR__.'/../lib/vendor/autoload.php';
$_POST variables are truncated

**Comment by voku** [comment]
Which version do you use + do you also use portable-utf8?

**Comment by zomar76** [comment]
sorry, my bad old wersion 
voku/simple_html_dom             3.1.2   

on php 5.6.40 machine

**Comment by voku** [comment]
Please try to add ```define('PORTABLE_UTF8__DISABLE_AUTO_FILTER', 1);``` before you require the autoloader or update to the current version. Happy Coding! 😊
