### ISSUE TITLE
Parsing json variable in <script> leaves $domReplaceHelper values

### ISSUE THREAD

**Issue by ruud-altenburg** [voku/simple_html_dom#31]
#### What is this feature about (expected vs actual behaviour)?

I'm parsing a <script> variable containing json. Characters in  $domReplaceHelper apparently are replaced when the page is parsed but not restored when the data is returned. 

#### How can I reproduce it?

See [example.txt](https://github.com/voku/simple_html_dom/files/3223268/example.txt) for a real world script plus my (slightly crude) code to extract the data.

#### Does it take minutes, hours or days to fix?

I suppose minutes.

#### Any additional information?

**Comment by ruud-altenburg** [comment]
Forgot to add that the example returns "RBR Holt 00626 ____SIMPLE_HTML_DOM__VOKU__AMP____ RBR Holt 00732".

**Comment by voku** [comment]
here I added a test-case for your problem: https://github.com/voku/simple_html_dom/commit/2e65479006175611c90dd248dc6dd88a57806113#diff-f9e35e3ee28495a595a36e0f7a4ae154R1454

The main problem here is that we need to use special internal encoding, to keep the input encoding, but we need to decode this internal encoding via "HtmlDomParser->fixHtmlOutput()"
