### ISSUE TITLE
cannot use if as in original version

### ISSUE THREAD

**Issue by stanislavdavid** [voku/simple_html_dom#35]
Thank for great work. 
#### What is this feature about (expected vs actual behaviour)?
I cannot use 
```
if ($html->find('tag')) {
    echo "Tag exists";
} else {
    echo "Tag not exists";
}
```
it is everytime TRUE even when tag not exists

#### Does it take minutes, hours or days to fix?
I Do not know

**Comment by voku** [comment]
please use ```findMultiOrFalse()``` or ```findOneOrFalse()``` (since version 4.7.x)

**Comment by stanislavdavid** [comment]
Please may you put it to README.md it is quite important change :-)

**Comment by voku** [comment]
It's updated 👍

Happy Coding!
