### ISSUE TITLE
Get recommendation rating from sidebar in Yahoo Finance

### ISSUE THREAD

**Issue by bte234** [voku/simple_html_dom#56]
I am trying to scrape the recommendation rating that is provided in Yahoo Finance.
Example page: https://finance.yahoo.com/quote/BYND/analysis?p=BYND
On the side of the page you can find the recommendation rating as shown below
![image](https://user-images.githubusercontent.com/26082352/94600220-72af7600-0246-11eb-9f6d-a6b665fd2124.png)
The structure of the part looks something like this:
![image](https://user-images.githubusercontent.com/26082352/94600459-c3bf6a00-0246-11eb-9b05-ee7aebdef75f.png)
When I try to get $html->find('.YDC-Col2'), I instead got some JS code:
![image](https://user-images.githubusercontent.com/26082352/94600680-19941200-0247-11eb-9b8e-8d829d906bcf.png)
When I try to see the value of $html->plaintext, I could see that the value I am looking for is under "recommendationMean"
![image](https://user-images.githubusercontent.com/26082352/94600949-91fad300-0247-11eb-9bfe-b78f073ab8fa.png)

Hence, I want to know how I could get this value out of $html. Thank you so much in advance.

**Comment by bte234** [comment]
Update: the reason I got JS code was because I mistakenly return the plainText of the result rather than the innerText. If i do

```
$result = $html->find('YDC-Col2');
return $result->innerText;
```

I instead got this:
![image](https://user-images.githubusercontent.com/26082352/94603183-c3c16900-024a-11eb-8eb8-38d41f916606.png)
I still am not able to get the value I need though.

**Comment by voku** [comment]
@bte234 You need to fetch the code with a headless browser first, because the site is using JavaScript to render the page. (https://github.com/voku/simple_html_dom/blob/59320931f0313752feca1c968910fec440a6a337/tests/SimpleHtmlDomTest.php#L433)

But sometimes everything looks like a nail because we have the hammer: 

```php
<?php

$json = file_get_contents('https://query2.finance.yahoo.com/v11/finance/quoteSummary/BYND?formatted=true&crumb=&lang=en-US&region=US&modules=financialData&corsDomain=finance.yahoo.com');
$array = json_decode($json, true);

echo $array['quoteSummary']['result'][0]['financialData']['recommendationMean']['raw'];
```

**Comment by bte234** [comment]
Thank you so much for your response. I was not aware of the API request for that one!
