### ISSUE TITLE
scrape table from filter

### ISSUE THREAD

**Issue by timobetz-webdesign** [voku/simple_html_dom#72]
Hi,

I want to get the table from this url:
https://www.hvw-online.org/spielbetrieb/ergebnissetabellen#/league?ogId=3&pId=83&lId=45926
I guess the is a problem with special characters maybe? Anyone an idea?

regards,
Timo

**Comment by voku** [comment]
"ngRepeat" ... sounds like Angular as Frontend Framework, so you can't get the html via curl or something like that because there is no html. The browser will build the page for you.

You could maybe use chrome headless to fetch the html?
