### ISSUE TITLE
Remove content based on child element

### ISSUE THREAD

**Issue by itajackass** [voku/simple_html_dom#74]
Hi i ond't find a way to remove a row table where a child has a class.

For example if I need to remove all rows with a cell with inside a span with class ".delete", i don't know how to do that.

```
<table>
<tr>
<td>
 text 1
</td>
<td>
 <span class="delete">DELETE</span>
</td>
</tr>
<tr>
<td>
 text 2
</td>
<td>
</td>
</tr>
<tr>
<td>
 text 3
</td>
<td>
 <span class="delete">DELETE</span>
</td>
</tr>
</table>
```

I tried this without success:

```
foreach ($dom->find('.delete').closest("tr") as $row) {
        $row->outertext = '';
    }
```

**Comment by voku** [comment]
Sorry for not getting back to you sooner: here is an example https://github.com/voku/simple_html_dom/commit/031f04327b9b0d28c54b57c069b73a3d9934c42f
