### ISSUE TITLE
Create/insert nodes?

### ISSUE THREAD

**Issue by gijo-varghese** [voku/simple_html_dom#79]
Is it possible to create or insert nodes?

For example, create a meta tag and add it to the `<head>` tag.

**Comment by voku** [comment]
Hi, I added a new example for you here: https://github.com/voku/simple_html_dom/blob/master/example/example_add_content.php

Do you already have some code to share? It's mostly more easily to help if you can show what you already tried, thanks.

**Comment by gijo-varghese** [comment]
@voku great, this should work. Are the newly added elements discoverable on parsing?

For example, I add a `<img src...>` inside the `<body>` using `innerhtml`. Can find it using `$dom->findOne('body img')`?

**Comment by voku** [comment]
Yes, that works. And everything is in body so that you can use "img" directly.

**Comment by gijo-varghese** [comment]
Great thank!
